[profile.default]
auto_detect_solc = false
evm_version = "shanghai"
optimizer = true
optimizer_runs = 10_000
out = "out"
script = "script"
solc = "0.8.29"
src = "src"
test = "tests"

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

[rpc_endpoints]
minato = "${MINATO_RPC_URL}"
soneium = "${SONEIUM_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
