[profile.default]
  auto_detect_solc = false
  evm_version = "shanghai"
  optimizer = true
  optimizer_runs = 10_000
  out = "out"
  script = "script"
  solc = "0.8.29"
  src = "src"
  test = "tests"
  ffi = true
  fs_permissions = [
    { access = "read", path = "./tests/fixtures/" },
    { access = "read-write", path = "./deployments" }
  ]

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

[etherscan]
  mainnet = { key = "${API_KEY_ETHERSCAN}" }
  holesky = { key = "${API_KEY_ETHERSCAN}" }
  sepolia = { key = "${API_KEY_ETHERSCAN}" }

[rpc_endpoints]
  minato = "${MINATO_RPC_URL}"
  soneium = "${SONEIUM_RPC_URL}"
  base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
  mainnet = "https://eth-mainnet.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
  holesky = "https://eth-holesky.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
