[profile.default]
  auto_detect_solc = false
  block_timestamp = 1_738_368_000 # Feb 1, 2025 at 00:00 GMT
  evm_version = "shanghai"
  optimizer = true
  optimizer_runs = 10_000
  out = "out"
  script = "script"
  solc = "0.8.30"
  src = "src"
  test = "tests"
  ffi = true
  fs_permissions = [
    { access = "read", path = "./tests/fixtures/" },
    { access = "read-write", path = "./deployments" }
  ]

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

[etherscan]
  mainnet = { key = "${ETHERSCAN_API_KEY}" }
  holesky = { key = "${ETHERSCAN_API_KEY}" }
  sepolia = { key = "${ETHERSCAN_API_KEY}" }

[rpc_endpoints]
  anvil = "http://127.0.0.1:8545"
  minato = "${MINATO_RPC_URL}"
  soneium = "${SONEIUM_RPC_URL}"
  base_sepolia = "https://base-sepolia.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
  base = "https://base-mainnet.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
  mainnet = "https://eth-mainnet.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
  holesky = "https://eth-holesky.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
  op_sepolia = "https://opt-sepolia.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
